#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_AVS = {{
//++Autogenerated -- start of section automatically generated
"__END__ __end__ bool catch clip else false float for func function global if int last no return string true try val "
"while yes "

, // 1 internal functions
"Abs( Acos( Apply( Asin( Assert( Atan( Atan2( AudioLengthHi( AudioLengthLo( "
"AverageB( AverageChromaU( AverageChromaV( AverageG( AverageLuma( AverageR( "
"BDifference( BDifferenceFromPrevious( BDifferenceToNext( BPlaneMax( BPlaneMedian( BPlaneMin( BPlaneMinMaxDifference( "
"BitAnd( BitChange( BitChg( BitClear( BitClr( BitLRotate( BitLShift( BitNot( BitOr( "
"BitRRotateL( BitRShiftA( BitRShiftL( BitRShiftS( BitRShiftU( BitRol( BitRor( "
"BitSal( BitSar( BitSet( BitSetCount( BitShl( BitShr( BitTest( BitTst( BitXor( BuildPixelType( "
"Ceil( Chr( ChromaUDifference( ChromaVDifference( "
"ColorSpaceNameToPixelType( ContinuedDenominator( ContinuedNumerator( Cos( Cosh( "
"Default( Defined( Eval( Exist( Exp( FillStr( FindStr( Float( Floor( Fmod( Format( Frac( FunctionExists( "
"GDifference( GDifferenceFromPrevious( GDifferenceToNext( GEval( GImport( "
"GPlaneMax( GPlaneMedian( GPlaneMin( GPlaneMinMaxDifference( GScript( GetParity( GetProcessInfo( "
"Hex( HexValue( Import( Int( InternalFunctionExists( IsBool( IsClip( IsFloat( IsInt( IsString( IsVersionOrGreater( "
"LCase( LeftStr( "
"LoadCPlugin( LoadPlugin( LoadVFAPIPlugin( LoadVirtualDubPlugin( Load_Stdcall_Plugin( Log( Log10( LogMsg( "
"LumaDifference( "
"Max( MidStr( Min( MulDiv( NOP( Ord( Pi( Pow( "
"RDifference( RDifferenceFromPrevious( RDifferenceToNext( RGBDifference( RGBDifferenceFromPrevious( RGBDifferenceToNext( "
"RPlaneMax( RPlaneMedian( RPlaneMin( RPlaneMinMaxDifference( Rand( ReplaceStr( RevStr( RightStr( Round( "
"ScriptDir( ScriptDirUtf8( ScriptFile( ScriptFileUtf8( ScriptName( ScriptNameUtf8( "
"Select( SetCacheMode( SetLogParams( SetMaxCPU( SetMemoryMax( SetPlanarLegacyAlignment( SetWorkingDir( Sign( Sin( Sinh( "
"Spline( Sqrt( StrCmp( StrCmpi( StrFromUtf8( StrLen( StrToUtf8( String( "
"Tan( Tanh( Time( TrimAll( TrimLeft( TrimRight( "
"UCase( UDifferenceFromPrevious( UDifferenceToNext( UPlaneMax( UPlaneMedian( UPlaneMin( UPlaneMinMaxDifference( "
"Undefined( "
"VDifferenceFromPrevious( VDifferenceToNext( VPlaneMax( VPlaneMedian( VPlaneMin( VPlaneMinMaxDifference( "
"Value( VarExist( VersionNumber( VersionString( "
"YDifferenceFromPrevious( YDifferenceToNext( YPlaneMax( YPlaneMedian( YPlaneMin( YPlaneMinMaxDifference( "
"_Combed( _SceneChangeNext( _SceneChangePrev( "
"propDelete( "
"propGetAny( propGetAsArray( propGetDataSize( propGetFloat( propGetInt( propGetKeyByIndex( propGetString( propGetType( "
"propNumElements( propNumKeys( propSet( propSetArray( propSetFloat( propSetInt( propSetString( propShow( "

, // 2 internal filters
"AddBorders( AlignedSplice( Amplify( AmplifyDB( Animate( ApplyRange( "
"AssumeBFF( AssumeFPS( AssumeFieldBased( AssumeFrameBased( AssumeSampleRate( AssumeScaledFPS( AssumeTFF( "
"AudioDub( AudioDubEx( AudioTrim( AviFileSource( AviSource( "
"BicubicResize( BilinearResize( BlackmanResize( Blackness( BlankClip( Blur( Bob( "
"ChangeFPS( ColorBars( ColorBarsHD( ColorKeyMask( ColorYUV( Compare( ComplementParity( "
"ConditionalFilter( ConditionalReader( ConditionalSelect( "
"ConvertAudioTo16bit( ConvertAudioTo24bit( ConvertAudioTo32bit( ConvertAudioTo8bit( ConvertAudioToFloat( "
"ConvertBackToYUY2( ConvertFPS( ConvertToMono( ConvertToPlanarRGB( ConvertToPlanarRGBA( "
"ConvertToRGB( ConvertToRGB24( ConvertToRGB32( ConvertToRGB48( ConvertToRGB64( ConvertToY( ConvertToY8( "
"ConvertToYUV420( ConvertToYUV422( ConvertToYUV444( ConvertToYUY2( "
"ConvertToYV12( ConvertToYV16( ConvertToYV24( ConvertToYV411( Crop( CropBottom( "
"DelayAudio( DeleteFrame( DirectShowSource( Dissolve( DoubleWeave( DuplicateFrame( Echo( EnsureVBRMP3Sync( "
"FadeIO( FadeIO0( FadeIO2( FadeIn( FadeIn0( FadeIn2( FadeOut( FadeOut0( FadeOut2( "
"FixBrokenChromaUpsampling( FixLuminance( FlipHorizontal( FlipVertical( FrameEvaluate( FreezeFrame( "
"GaussResize( GeneralConvolution( GetChannel( GetChannels( GetLeftChannel( GetRightChannel( Grayscale( Greyscale( "
"Histogram( HorizontalReduceBy2( ImageReader( ImageSource( ImageSourceAnim( ImageWriter( Info( Interleave( Invert( "
"KillAudio( KillVideo( Lanczos4Resize( LanczosResize( Layer( Letterbox( Levels( Limiter( Loop( "
"Mask( MaskHS( Merge( MergeARGB( MergeChannels( MergeChroma( MergeLuma( MergeRGB( MessageClip( MixAudio( MonoToStereo( "
"Normalize( OpenDMLSource( Overlay( PeculiarBlend( PointResize( Preroll( Pulldown( "
"RGBAdjust( ReduceBy2( ResampleAudio( ResetMask( Reverse( "
"SSRC( ScriptClip( SegmentedAviSource( SegmentedDirectShowSource( SelectEven( SelectEvery( SelectOdd( SelectRangeEvery( "
"SeparateColumns( SeparateFields( SeparateRows( "
"Sharpen( ShowAlpha( ShowBlue( ShowFiveVersions( ShowFrameNumber( ShowGreen( ShowRed( ShowSMPTE( ShowTime( SincResize( "
"SkewRows( SpatialSoften( Spline16Resize( Spline36Resize( Spline64Resize( StackHorizontal( StackVertical( "
"Subtitle( Subtract( SuperEQ( SwapFields( SwapUV( "
"TCPServer( TCPSource( TemporalSoften( TimeStretch( Tone( Trim( Turn180( TurnLeft( TurnRight( Tweak( "
"UToY( UToY8( UnalignedSplice( VToY( VToY8( Version( VerticalReduceBy2( "
"WavSource( Weave( WeaveColumns( WeaveRows( WriteFile( WriteFileEnd( WriteFileIf( WriteFileStart( YToUV( "

, // 3 external filters
"ASTDR( ASTDRmc( ASharp( AdaptiveMedian( AddAudio( AddGrain( AddGrainC( AddlogoHD( AnalyzeLogo( Anime4KCPP( AnimeIVTC( "
"ApparentFPS( ApplyEvery( ApplyGradationCurves( ApplyInterlacedFilter( AreaResize( AssRender( "
"AudioGraph( AudioMax( AudioMin( AudioRMS( AudioTimeline( AutoCrop( Average( AverageBlur( AvsMotion( "
"BWDIF( BackwardClense( Barrel( Befa( BestAudioSource( Bifrost( BinomialBlur( BlindDeHalo3( BorderControl( "
"BucketMedian( Butteraugli( "
"CAS( CacheAudio( CallCmd( Cdeblend( Cdeint( "
"ChanMix( ChannelMixer( Checkmate( ChromaShift( ChromaShiftSP( ChubbyRain( ChubbyRain2( "
"Clense( ClipBlend( ClipBlend16( ClipClop( Cnr2( "
"ColorBalance( ColorDiff( ColorMatrix( ColorRangeMask( Colorize( ColourMask( ColourStabilise( ColourWarp( "
"CombMask( CombMask2( ConditionalFilterMT( ContinuityFixer( ContinuousMask( "
"Convert60ito24p( ConvertFpsLimit( ConvertFromShader( ConvertToShader( CoronaSequence( Cube( "
"DCTFilter( DCTFilter4( DCTFilter4D( DCTFilter8( DCTFilter8D( DCTFilterD( DCTFun4b( DCTFun4c( DCTFun5( DFMDeRainbow( "
"DGHDRtoSDR( DGHable( DGPQtoHLG( DGReinhard( DSS2( DeBlend( DeBlock_QED( DeCrawl( DeCross( DeDot( DeGrainMedian( "
"DeHaloHmod( DeHalo_alpha( DeNoise( DePulse( DeRainbow( DeRainbowYUY2( DeSaltPepper( DeSpot( Deathray( "
"Debicubic( DebicubicY( Debilinear( DebilinearY( DeblendLogo( Deblock( DeblockPP7( DecombUCF( Deen( Defish( Deflicker( "
"DeleteEvery( DeleteFrames( DelogoHD( Depansafe( Deshaker3D( Deskew( DistanceFunction( DumpPixelValues( Dup1( DupStep( "
"EEDI2( EdgeCleaner( EffectsMany( EquLines( "
"ExInpaint( ExactDedup( Exblend( ExecuteShader( ExpotencialLimiter( ExtendedBilateral( "
"F1Quiver( F3kGrain( FCBI( FDecimate( FDecimate2( FFT3DFilter( FFT3DGPU( FFTSpectrum( FFmpegSource2( FastBlur( "
"FieldHint( FileSize( FillBorders( FillMargins( FineDehalo( FineSharp( Fingerprint( "
"FixBlendIVTC( FixChromaBleeding( FixChromaBleedingMod( FixChromaticAberration( FixFPS( FluxSmoothST( FluxSmoothT( "
"ForwardClense( FrFun3b( FrFun3d( FrFun7( FrameDbl( FrameRateConverter( FrameRepeat( FrameSel( FreeSub( FunkyDeBlock( "
"GBlur( GNoise( GaussianBlur( GetMTMode( GetProgramName2( Ghostbuster( GiCoCu( "
"GraMaMa( GradFun2DB( GradFun2DBmod( GrainFactory3( Grid( "
"HDRAGC( HQDering( HQDeringmod( HQdn3d( HSIAdjust( HSLAdjust( HSVAdjust( HShear( HistogramCMYLevels( HistogramRGBLevels( "
"Hue( Hysteria( "
"IT( Info2( InpaintAssist( InpaintFunc( InpaintLogo( "
"InterlacedResize( InterlacedWarpedResize( InterleaveEvery( InterpolateDoubles( IsCombed2( IsHinted( "
"Jinc144Resize( Jinc256Resize( Jinc36Resize( Jinc64Resize( JincResize( JpegSource( KNLMeansCL( KillHints( KillPulse( "
"LGhost( LSFmod( LUTDeCrawl( LUTDeRainbow( LazyDering( LeakKernelBob( LeakKernelDeint( LengthenClip( "
"LimitedSharpenFaster( LinearLimiter( LoadDLL( LumaYV12( "
"MCTemporalDenoise( MC_Spuds( MDEC2( MDeblock( MPEG2Source( MPlayerNoise( MSCDetection( MSharpen( MT( MTi( MTsource( "
"MaskSub( MaskSubMod( MaskedMerge2( MatchHistogram( MaxCLLFind( Median( MedianBlur( MedianBlurTemporal( MiniDeen( "
"MosquitoNR( MoveChroma( "
"NicAC3Source( NicDTSSource( NicLPCMSource( NicMPG123Source( NoiseGenerator( NonlinUSM( Normalize2( "
"OutRange( OverlayCompare( OverlayConfig( OverlayEngine( OverlayRender( "
"PackedToPlanar( PixelScope( PlanarToRGB32( Posterize( Prune( QTInput( "
"RAverageM( RAverageW( RGBColourStabilise( RGBToRGB( RMerge( RaWavSource( Rainbow_Smooth( RawSequence( RawSource( ReCon( "
"ReInterpolate411( ReduceFlicker( ReferenceFixerFixer( RemapFrames( RemapFramesSimple( RemoveGrain( "
"Repair( RepeatEveryFrame( ReplaceFramesSimple( Resize8( RestoreFPS( RestoreMotionBlocks( RoboCrop( Rotate( "
"SCXvid( SCXvidMask( SPresso( SSHiQ( SSIM( SSIM_FRAME( SSIM_U_FRAME( SSIM_V_FRAME( SSIM_Y_FRAME( SSIQ( SSSharp( "
"STMedianFilter( STPresso( SangNom2( Scanlines( SeeSaw( SegmentedAmp( SelectiveColour( Sepia( SetMTmode( "
"Shader( ShowOverRange( ShowPixelValues( SickJumps( SimpleResize( Skew( SmartSSIQ( SmoothD( SmoothD2( SmoothUV( "
"SoftLight( Soothe( SoxFilter( SpecificEffectName( Spectrogram( Stab( StaticNoiseC( StripeMask( "
"SubtitleEx( SupTitle( SuperToon( "
"TBilateral( TCannyMod( TColorMask( TComb( TCombMask( TDeint( TEMmod( TEdgeMask( TIsophote( TMM( TMM2( TMaskCleaner( "
"TNLMeans( TTempSmooth( TTempSmoothF( TUnsharp( Technicolor( TelecideHints( "
"TempGaussMC_beta2( TempLinearApproximate( TemporalDegrain( TemporalRepair( "
"TextSub( TextSubMod( TextSubModSwapUV( TextSubSwapUV( TimecodeFPS( Toon( ToonLite( Transition( TurnsTile( "
"TweakColor( TweakHist( "
"UnDot( UnFilter( Unpremultiply( Unsharp( UnsharpHQ( "
"VFRtoCFR( VMAF( VSEval( VSImport( VShear( VagueDenoiser( VerticalCleaner( VfrToCfr( "
"VideoScope( ViewAudio( Vinverse( Vinverse2( VobSub( "
"WarpedResize( Watermark2( WavGainLimiter( Waveform( WhileEval( WhiteBalance( YAHR( YARK( YFRC( YV12To422( Yadif( Zoom( "
"_2DCleanYUY2( aSobel( aWarpSharpDering( abcxyz( caf( cc( cl_expr( cl_exprxy( cl_exprxyz( deVCR( descratch( dftTest( "
"ffdshow( ffdshowAudio( ivtc_txt60mc( listGPUs( maa2( mfRainbow( mfToon2( mfToonLite( mrestore( mt_YRangeMask( mt_edge( "
"neo_vd( nnedi3( nnedi3_rpow2( nnedi3ocl( pSharpen( proToon( removeblend( rm_logo( salFPS3( santiag( scharr( srestore( "
"tcanny( uu_mt_blend( vmToon( vsDeblockPP7( vsMSharpen( vsMSmooth( vsTTempSmooth( xaa( yadifmod( yadifmod2( "
"z_BicubicResize( z_BilinearResize( z_ConvertFormat( z_Lanczos4Resize( z_LanczosResize( z_PointResize( "
"z_Spline16Resize( z_Spline36Resize( z_Spline64Resize( "

, // 4 properties
"AudioBits AudioChannels AudioDuration AudioLength AudioLengthF AudioLengthS AudioRate BitsPerComponent ComponentSize "
"FrameCount FrameRate FrameRateDenominator FrameRateNumerator HasAlpha HasAudio HasVideo Height "
"Is420 Is422 Is444 IsAudioFloat IsAudioInt IsFieldBased IsFrameBased IsInterleaved "
"IsPackedRGB IsPlanar IsPlanarRGB IsPlanarRGBA IsRGB IsRGB24 IsRGB32 IsRGB48 IsRGB64 "
"IsY IsY8 IsYUV IsYUVA IsYUY2 IsYV12 IsYV16 IsYV24 IsYV411 "
"NumComponents PixelType Width "
"_AbsoluteTime _ChromaLocation _ColorRange _DurationDen _DurationNum _Field _FieldBased _Matrix _PictType _Primaries "
"_SARDen _SARNum _Transfer "

, // 5 options
"OPT_AVIPadScanlines OPT_AllowFloatAudio "
"OPT_Enable_PlanarToPackedRGB OPT_Enable_V210 OPT_Enable_Y3_10_10 OPT_Enable_Y3_10_16 OPT_Enable_b64a "
"OPT_UseWaveExtensible OPT_VDubPlanarHack OPT_dwChannelMask( "

, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_AVS[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_AVS_KEYWORD, NP2StyleX_Keyword, L"bold; fore:#FF8000" },
	{ SCE_AVS_FUNCTION, NP2StyleX_BuiltInFunction, L"fore:#0080C0" },
	{ SCE_AVS_FILTER, NP2StyleX_InternalFilter, L"fore:#648000" },
	{ SCE_AVS_PLUGIN, NP2StyleX_ExternalFilter, L"fore:#7C5AF3" },
	{ SCE_AVS_CLIPPROP, NP2StyleX_Property, L"fore:#007F7F" },
	{ SCE_AVS_USERDFN, NP2StyleX_Function, L"fore:#A46000" },
	{ MULTI_STYLE(SCE_AVS_COMMENTLINE, SCE_AVS_COMMENTBLOCK, SCE_AVS_COMMENTBLOCKN, 0), NP2StyleX_Comment, L"fore:#608060" },
	{ MULTI_STYLE(SCE_AVS_STRING, SCE_AVS_ESCAPESTRING, 0, 0), NP2StyleX_String, L"fore:#008000" },
	{ SCE_AVS_TRIPLESTRING, NP2StyleX_TripleQuotedString, L"fore:#F08000" },
	{ SCE_AVS_ESCAPECHAR, NP2StyleX_EscapeSequence, L"fore:#0080C0" },
	{ SCE_AVS_NUMBER, NP2StyleX_Number, L"fore:#FF0000" },
	{ SCE_AVS_OPERATOR, NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexAVS = {
	SCLEX_AVS, NP2LEX_AVS,
	EDITLEXER_HOLE(L"AviSynth Script", Styles_AVS),
	L"avs; avsi",
	&Keywords_AVS,
	Styles_AVS
};
