#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_NULL = {{
nullptr
}};

static EDITSTYLE Styles_Global[] = {
	{ STYLE_DEFAULT, NP2StyleX_DefaultCodeStyle, L"font:$(Code)" },
	{ STYLE_DEFAULT, NP2StyleX_DefaultTextStyle, L"font:$(Text)" },
	{ STYLE_LINENUMBER, NP2StyleX_MarginLineNumber, L"size:-2; fore:#2B91AF" },
	{ 0, NP2StyleX_MatchingBrace, L"fore:#02EA0A; alpha:50; outline:200" },
	{ 0, NP2StyleX_MatchingBraceError, L"fore:#FF0000; alpha:50; outline:200" },
	{ STYLE_CONTROLCHAR, NP2StyleX_ControlCharacter, L"size:-1; fore:#108010; back:#228B22" },
	{ STYLE_INDENTGUIDE, NP2StyleX_IndentationGuide, L"fore:#FF8000" },
	{ SC_ELEMENT_SELECTION_BACK, NP2StyleX_SelectedText, L"eolfilled; alpha:95; outline:50" },
	{ SC_ELEMENT_WHITE_SPACE, NP2StyleX_Whitespace, L"size:2; fore:#FF4000; alpha:65" },
	{ SC_ELEMENT_CARET_LINE_BACK, NP2StyleX_CurrentLine, L"size:2; fore:#C2C0C3; back:#FFFF00; alpha:90; outline:90" },
	{ SC_ELEMENT_CARET, NP2StyleX_Caret, L"back:#FF0000" },
	{ INDICATOR_IME, NP2StyleX_IMEIndicator, L"fore:#108010" },
	{ SCI_SETEDGECOLOUR, NP2StyleX_LongLineMarker, L"fore:#FFC000" },
	{ SCI_SETEXTRAASCENT + SCI_SETEXTRADESCENT, NP2StyleX_ExtraLineSpacing, L"size:2" },
	{ 0, NP2StyleX_CodeFolding, L"" },
	{ SC_MARKNUM_FOLDER, NP2StyleX_FoldingMarker, L"fore:#8080FF; back:#ADD8E6" },
	{ STYLE_FOLDDISPLAYTEXT, NP2StyleX_FoldEllipsis, L"font:$(Code); size:-2; bold; fore:#808080" },
	{ 0, NP2StyleX_MarkOccurrences, L"alpha:25; outline:150" },
	{ SC_MARK_VERTICALBOOKMARK, NP2StyleX_Bookmark, L"fore:#408040; back:#00FF00; alpha:40" },
	{ SC_MARKNUM_HISTORY_SAVED + SC_MARKNUM_HISTORY_MODIFIED, NP2StyleX_ChangeHistoryMarker, L"fore:#008000; back:#0080FF" },
	{ STYLE_CALLTIP, NP2StyleX_CallTip, L"" },
	{ STYLE_LINK, NP2StyleX_Link, L"fore:#648000" },
};

EDITLEXER lexGlobal = {
	SCLEX_NULL, NP2LEX_GLOBAL,
	SCHEME_SETTINGS_DEFAULT,
	EDITLEXER_HOLE(L"Global Styles", Styles_Global),
	nullptr,
	nullptr,
	Styles_Global
};

static EDITSTYLE Styles_Text[] = {
	EDITSTYLE_DEFAULT,
};

static EDITSTYLE Styles_2ndText[] = {
	EDITSTYLE_DEFAULT,
};

EDITLEXER lexTextFile = {
	SCLEX_NULL, NP2LEX_TEXTFILE,
//Text Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_NoBlockComment |
		LexerAttr_IndentBasedFolding |
		LexerAttr_IndentLookForward |
		LexerAttr_PlainTextFile,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 1) | (1 << 2), // level1, level2
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, 0,
		0, 0,
//Text Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_TEXT(L"Text File", Styles_Text),
	L"txt; text; wtx; doc",
	&Keywords_NULL,
	Styles_Text
};

EDITLEXER lex2ndTextFile = {
	SCLEX_NULL, NP2LEX_2NDTEXTFILE,
//2nd Text Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_NoBlockComment |
		LexerAttr_IndentBasedFolding |
		LexerAttr_IndentLookForward |
		LexerAttr_PlainTextFile,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 1) | (1 << 2), // level1, level2
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, 0,
		0, 0,
//2nd Text Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"2nd Text File", Styles_2ndText),
	L"log; asc; map; bnf",
	&Keywords_NULL,
	Styles_2ndText
};

static EDITSTYLE Styles_ANSI[] = {
	// override font used in global styles to ensure line height is same as measured from STYLE_DEFAULT.
	// negative extra line spacing is required when using Direct2D, not required when using GDI.
	{ STYLE_DEFAULT, NP2StyleX_Default, L"font:Lucida Console" },
	{ STYLE_LINENUMBER, NP2StyleX_MarginLineNumber, L"font:Lucida Console" },
	{ SCI_SETEXTRAASCENT + SCI_SETEXTRADESCENT, NP2StyleX_ExtraLineSpacing, L"size:-1" },
	{ STYLE_FOLDDISPLAYTEXT, NP2StyleX_FoldEllipsis, L"font:Lucida Console" },
};

EDITLEXER lexANSI = {
	SCLEX_NULL, NP2LEX_ANSI,
//ANSI Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_NoBlockComment |
		LexerAttr_IndentBasedFolding |
		LexerAttr_IndentLookForward |
		LexerAttr_PlainTextFile,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 1) | (1 << 2), // level1, level2
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, 0,
		0, 0,
//ANSI Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"ANSI Art", Styles_ANSI),
	L"nfo; diz",
	&Keywords_NULL,
	Styles_ANSI
};

static EDITSTYLE Styles_Config[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_CONF_SECTION, NP2StyleX_Section, L"bold; back:#FFC040; eolfilled" },
	{ SCE_CONF_DIRECTIVE, NP2StyleX_Directive, L"fore:#003CE6" },
	{ SCE_CONF_COMMENT, NP2StyleX_Comment, L"fore:#008000" },
	{ SCE_CONF_STRING, NP2StyleX_String, L"fore:#B000B0" },
	{ MULTI_STYLE(SCE_CONF_NUMBER, SCE_CONF_HEXNUM, 0, 0), NP2StyleX_Number, L"fore:#FF4000" },
	//{ SCE_CONF_IP, EDITSTYLE_HOLE(L"IP Address"), L"bold; fore:#FF4000" },
	//{ SCE_CONF_IDENTIFIER, EDITSTYLE_HOLE(L"Identifier"), L"" },
	{ SCE_CONF_OPERATOR, NP2StyleX_Operator, L"fore:#B000B0" },
	//{ SCE_CONF_PARAMETER, EDITSTYLE_HOLE(L"Runtime Directive Parameter"), L"" },
	//{ SCE_CONF_EXTENSION, EDITSTYLE_HOLE(L"Extension"), L"" },
};

EDITLEXER lexConfig = {
	SCLEX_CONFIG, NP2LEX_CONFIG,
//Config Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoBlockComment,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1), // level1, level2
		0,
		'\\', 0, 0,
		0,
		0, 0,
		SCE_CONF_OPERATOR, 0,
		KeywordAttr_Default
		, SCE_CONF_COMMENT,
		0, 0,
//Config Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Config File", Styles_Config),
	L"conf; cfg; cnf; htaccess; properties; prefs; iface; prop; po; te",
	&Keywords_NULL,
	Styles_Config
};

static EDITSTYLE Styles_CSV[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_CSV_COLUMN_0, NP2StyleX_Column1, L"fore:#E24000" },
	{ SCE_CSV_COLUMN_1, NP2StyleX_Column2, L"fore:#FF8000" },
	{ SCE_CSV_COLUMN_2, NP2StyleX_Column3, L"fore:#C08000" },
	{ SCE_CSV_COLUMN_3, NP2StyleX_Column4, L"fore:#008000" },
	{ SCE_CSV_COLUMN_4, NP2StyleX_Column5, L"fore:#008080" },
	{ SCE_CSV_COLUMN_5, NP2StyleX_Column6, L"fore:#0080FF" },
	{ SCE_CSV_COLUMN_6, NP2StyleX_Column7, L"fore:#7C5AF3" },
	{ SCE_CSV_COLUMN_7, NP2StyleX_Column8, L"fore:#A46000" },
	{ SCE_CSV_COLUMN_8, NP2StyleX_Column9, L"fore:#648000" },
	{ SCE_CSV_COLUMN_9, NP2StyleX_Column10, L"fore:#408080" },
	{ SCE_CSV_DELIMITER, NP2StyleX_Delimiter, L"fore:#608060" },
};

EDITLEXER lexCSV = {
	SCLEX_CSV, NP2LEX_CSV,
//CSV Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_NoBlockComment |
		LexerAttr_PlainTextFile,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1), // level1, level2
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, 0,
		0, 0,
//CSV Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"CSV File", Styles_CSV),
	L"csv; tsv",
	&Keywords_NULL,
	Styles_CSV
};

static EDITSTYLE Styles_Diff[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_DIFF_COMMENT, NP2StyleX_Comment, L"fore:#008000" },
	{ SCE_DIFF_COMMAND, NP2StyleX_Command, L"bold; fore:#0A246A" },
	{ SCE_DIFF_HEADER, NP2StyleX_SourceDestination, L"fore:#C80000; back:#FFF1A8; eolfilled" },
	{ SCE_DIFF_POSITION, NP2StyleX_PositionSetting, L"fore:#0000FF" },
	{ MULTI_STYLE(SCE_DIFF_ADDED, SCE_DIFF_PATCH_ADD, SCE_DIFF_REMOVED_PATCH_ADD, 0), NP2StyleX_LineAddition, L"fore:#002000; back:#80FF80; eolfilled" },
	{ MULTI_STYLE(SCE_DIFF_DELETED, SCE_DIFF_PATCH_DELETE, SCE_DIFF_REMOVED_PATCH_DELETE, 0), NP2StyleX_LineRemoval, L"fore:#200000; back:#FF8080; eolfilled" },
	{ SCE_DIFF_CHANGED, NP2StyleX_LineChange, L"fore:#000020; back:#8080FF; eolfilled" },
};

EDITLEXER lexDiff = {
	SCLEX_DIFF, NP2LEX_DIFF,
//Diff Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_NoBlockComment |
		LexerAttr_PlainTextFile,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 2), // command, [file], diff
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, SCE_DIFF_COMMENT,
		0, 0,
//Diff Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Diff File", Styles_Diff),
	L"diff; patch",
	&Keywords_NULL,
	Styles_Diff
};

static EDITSTYLE Styles_INI[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_PROPS_SECTION, NP2StyleX_Section, L"bold; back:#FFC040; eolfilled" },
	{ SCE_PROPS_KEY, NP2StyleX_Property, L"fore:#A46000" },
	{ SCE_PROPS_COMMENT, NP2StyleX_Comment, L"fore:#008000" },
	{ SCE_PROPS_ASSIGNMENT, NP2StyleX_Assignment, L"fore:#FF0000" },
	{ SCE_PROPS_DEFVAL, NP2StyleX_DefaultValue, L"fore:#FF0000" },
};

EDITLEXER lexINI = {
	SCLEX_PROPERTIES, NP2LEX_INI,
//Ini Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoBlockComment,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1), // section, comment
		0,
		'\0', 0, 0,
		0,
		0, 0,
		0, 0,
		KeywordAttr_Default
		, SCE_PROPS_COMMENT,
		0, 0,
//Ini Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Ini Config File", Styles_INI),
	L"ini; inf; reg; oem; sif; url; sed; theme; clw; abnf",
	&Keywords_NULL,
	Styles_INI
};
