#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_Elixir = {{
//++Autogenerated -- start of section automatically generated
"after alias and case catch cond def defmacro defmodule defp defstruct do else end false fn for if import in nil not or "
"quote raise receive require rescue true try use when with "

, // 1 annotations
nullptr

, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_Elixir[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_ERLANG_KEYWORD, NP2StyleX_Keyword, L"bold; fore:#FF8000" },
	{ SCE_ERLANG_PREPROCESSOR, NP2StyleX_Annotation, L"fore:#C65D09" },
	{ SCE_ERLANG_RECORD, NP2StyleX_Structure, L"fore:#0080FF" },
	{ SCE_ERLANG_FUNCTION, NP2StyleX_Function, L"fore:#A46000" },
	{ SCE_ERLANG_COMMENTLINE, NP2StyleX_Comment, L"fore:#608060" },
	{ MULTI_STYLE(SCE_ERLANG_CHARACTER, SCE_ERLANG_STRING_SQ, SCE_ERLANG_STRING_DQ, 0), NP2StyleX_String, L"fore:#008000" },
	{ MULTI_STYLE(SCE_ERLANG_TRIPLE_STRING_SQ, SCE_ERLANG_TRIPLE_STRING_DQ, SCE_ERLANG_TRIPLE_SIGIL_SQ, SCE_ERLANG_TRIPLE_SIGIL_DQ), NP2StyleX_TripleQuotedString, L"fore:#F08000" },
	{ MULTI_STYLE(SCE_ERLANG_SIGIL, SCE_ERLANG_VERBATIM_SIGIL, SCE_ERLANG_SIGIL_ID, 0), NP2StyleX_DelimitedString, L"fore:#E24000" },
	{ SCE_ERLANG_ESCAPECHAR, NP2StyleX_EscapeSequence, L"fore:#0080C0" },
	{ MULTI_STYLE(SCE_ERLANG_SYMBOL_ID, SCE_ERLANG_SYMBOL_OP, 0, 0), NP2StyleX_Symbol, L"fore:#7C5AF3" },
	{ SCE_ERLANG_NUMBER, NP2StyleX_Number, L"fore:#FF0000" },
	{ MULTI_STYLE(SCE_ERLANG_OPERATOR, SCE_ERLANG_OPERATOR2, 0, 0), NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexElixir = {
	SCLEX_ERLANG, NP2LEX_ELIXIR,
//Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoBlockComment |
		LexerAttr_IndentBasedFolding |
		LexerAttr_IndentLookForward,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 1), // function
		0,
		'\\', SCE_ERLANG_ESCAPECHAR, 0,
		0,
		0, SCE_ERLANG_CHARACTER,
		SCE_ERLANG_OPERATOR, SCE_ERLANG_OPERATOR2
		, KeywordAttr32(0, KeywordAttr_PreSorted) // keywords
		| KeywordAttr32(1, KeywordAttr_NoLexer | KeywordAttr_NoAutoComp) // annotations
		, SCE_ERLANG_COMMENTLINE,
		SCE_ERLANG_CHARACTER, SCE_ERLANG_ESCAPECHAR,
//Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Elixir Source", Styles_Elixir),
	L"ex; exs",
	&Keywords_Elixir,
	Styles_Elixir
};
