#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_TEX = {{
//++Autogenerated -- start of section automatically generated
"appendix begin caption chapter documentclass end label pageref paragraph part ref "
"section subparagraph subsection subsubsection title usepackage verb "

, // 1 misc
nullptr

, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_TEX[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_L_CHAPTER, NP2StyleX_Chapter, L"bold; fore:#0080FF" },
	{ SCE_L_SECTION, NP2StyleX_Section, L"bold; fore:#0066CC" },
	{ SCE_L_SECTION1, NP2StyleX_Subection, L"bold; fore:#0080C0" },
	{ SCE_L_SECTION2, NP2StyleX_Subsubection, L"bold; fore:#007F7F" },
	{ MULTI_STYLE(SCE_L_TITLE, SCE_L_TITLE_TOC, 0, 0), NP2StyleX_Title, L"bold; fore:#408080" },
	{ SCE_L_COMMAND, NP2StyleX_Command, L"fore:#0000FF" },
	{ SCE_L_MARCO, NP2StyleX_Macro, L"fore:#FF8000" },
	{ MULTI_STYLE(SCE_L_COMMENT, SCE_L_COMMENT2, 0, 0), NP2StyleX_Comment, L"fore:#608060" },
	{ MULTI_STYLE(SCE_L_MATH, SCE_L_MATH2, 0, 0), NP2StyleX_Math, L"fore:#FF4F0F" },
	{ MULTI_STYLE(SCE_L_SPECIAL, SCE_L_CATCODE, 0, 0), NP2StyleX_SpecialCharacter, L"fore:#3A6EA5" },
	{ MULTI_STYLE(SCE_L_TAG, SCE_L_TAG2, 0, 0), NP2StyleX_Tag, L"fore:#FF8000" },
	{ MULTI_STYLE(SCE_L_OPT_PARAM, SCE_L_MARCO_PARAM, 0, 0), NP2StyleX_Parameter, L"fore:#1E90FF" },
	{ MULTI_STYLE(SCE_L_VERBATIM, SCE_L_VERBATIM2, 0, 0), NP2StyleX_VerbatimSegment, L"fore:#666666" },
	{ SCE_L_LISTCODE, NP2StyleX_ListCode, L"fore:#808080" },
	{ SCE_L_OPERATOR, NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexLaTeX = {
	SCLEX_LATEX, NP2LEX_LATEX,
//Settings++Autogenerated -- start of section automatically generated
		LexerAttr_EscapePunctuation,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1) | (1 << 2), // chapter, section, subsection
		0,
		'\\', SCE_L_SPECIAL, 0,
		0,
		0, SCE_L_CATCODE,
		SCE_L_OPERATOR, 0
		, KeywordAttr32(0, KeywordAttr_NoLexer) // commands
		| KeywordAttr32(1, KeywordAttr_NoLexer) // misc
		, SCE_L_COMMENT2,
		0, 0,
//Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"LaTeX File", Styles_TEX),
	L"tex; latex; sty; cls; tpx; bbl; bib; bst; ltx; dtx; ins; info; isty; fd; rd; aux; toc; lof; lot; idx; ind",
	&Keywords_TEX,
	Styles_TEX
};
