#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_Mathematica = {{
//++Autogenerated -- start of section automatically generated
"Abort Begin BeginPackage Block Break Catch Continue Do End EndPackage False For Function If Interrupt Module Nest Null "
"Return Switch Table Throw True Until Which While With "

, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_Mathematica[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_MATHEMATICA_KEYWORD, NP2StyleX_Keyword, L"bold; fore:#FF8000" },
	{ MULTI_STYLE(SCE_MATHEMATICA_COMMENTLINE, SCE_MATHEMATICA_COMMENT, 0, 0), NP2StyleX_Comment, L"fore:#608060" },
	{ SCE_MATHEMATICA_STRING, NP2StyleX_String, L"fore:#008000" },
	//{ SCE_MATHEMATICA_ESCAPECHAR, NP2StyleX_EscapeSequence, L"fore:#0080C0" },
	{ SCE_MATHEMATICA_SLOT, NP2StyleX_Placeholder, L"fore:#8080FF" },
	{ SCE_MATHEMATICA_NUMBER, NP2StyleX_Number, L"fore:#FF0000" },
	{ SCE_MATHEMATICA_OPERATOR, NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexMathematica = {
	SCLEX_MATHEMATICA, NP2LEX_MATHEMATICA,
//Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoLineComment |
		LexerAttr_EscapePunctuation,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1), // level1, level2
		0,
		'\\', SCE_MARKDOWN_ESCAPECHAR, 0,
		0,
		0, SCE_MATHEMATICA_OPERATOR,
		SCE_MATHEMATICA_OPERATOR, 0
		, KeywordAttr32(0, KeywordAttr_PreSorted) // keywords
		, SCE_MATHEMATICA_COMMENT,
		SCE_MATHEMATICA_STRING, SCE_MATHEMATICA_ESCAPECHAR,
//Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Mathematica", Styles_Mathematica),
	L"nb; wl; wls",
	&Keywords_Mathematica,
	Styles_Mathematica
};
