#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_R = {{
//++Autogenerated -- start of section automatically generated
"FALSE Inf NA NA_character_ NA_complex_ NA_integer_ NA_real_ NULL NaN TRUE break else for function if in next repeat "
"while "

, // 1 package
"Arg( AutoloadEnv Autoloaded BaseNamespaceEnv Call( Complex( Conj( Cstack_info( Defunct( Deprecated( Device Devices "
"Encoding( External( Filter( Find( Fortran( GlobalEnv ISOdate( ISOdatetime( Internal( "
"LETTERS La.svd( La_library( La_version( Last.lib( Last.value Library Library.site Machine Map( Math( Mod( "
"NCOL( NROW( Negate( NextMethod( NotYetImplemented( NotYetUsed( OlsonNames( Ops( Options Platform Position( Primitive( "
"R.Version( R.home( R.version R.version.string RNGkind( RNGversion( R_system_version( Random.seed Recall( Reduce( "
"S3method( Summary( Sys.Date( Sys.chmod( Sys.getenv( Sys.getlocale( Sys.getpid( Sys.glob( Sys.info( Sys.junction( "
"Sys.localeconv( Sys.readlink( Sys.setFileTime( Sys.setenv( Sys.setlocale( Sys.sleep( Sys.time( Sys.timezone( "
"Sys.umask( Sys.unsetenv( Sys.which( "
"UseMethod( Vectorize( "
"abbreviate( abs( acos( activeBindingFunction( addNA( addTaskCallback( agrep( agrepl( "
"alist( all( all.equal( all.names( all.vars( allowInterrupts( any any( anyDuplicated( anyNA( aperm( append( apply( "
"args( array( arrayInd( as.Date( as.POSIXct( as.POSIXlt( as.array( as.call( as.character( as.complex( "
"as.data.frame( as.difftime( as.double( as.environment( as.expression( as.factor( as.function( as.hexmode( as.integer( "
"as.list( as.logical( as.matrix( as.name( as.null( as.numeric( as.octmode( as.ordered( as.pairlist( as.qr( as.raw( "
"as.single( as.symbol( as.table( as.vector( asS3( asS4( asin( asplit( assign( "
"atan( atan2( attach( attachNamespace( attr( attr.all.equal( attributes( autoload( autoloader( "
"backsolve( baseenv( basename( besselI( besselJ( besselK( besselY( beta( "
"bincode( bindingIsActive( bindingIsLocked( bindtextdomain( bitwAnd( bitwNot( bitwOr( bitwShiftL( bitwShiftR( bitwXor( "
"body( bquote( browser( browserCondition( browserSetDebug( browserText( builtin bytecode bzfile( "
"call( callCC( capabilities( casefold( cat( cbind( ceiling( "
"char char.expand( charToRaw( character character( charmatch( chartr( chkDots( chol( chol2inv( choose( "
"class( class2( clearPushBack( close( closeAllConnections( closure col( colMeans( colSums( colnames( "
"commandArgs( comment( complex complex( computeRestarts( "
"conditionCall( conditionMessage( conflictRules( conflicts( contributors( cos( cospi( crossprod( "
"cummax( cummin( cumprod( cumsum( curlGetHeaders( cut( "
"dQuote( data.class( data.frame( data.matrix( date( "
"debug( debuggingState( debugonce( delayedAssign( deparse( deparse1( deparseOpts( det( detach( determinant( dget( "
"diag( diff( difftime( digamma( dim( dimnames( dir( dir.create( dir.exists( dirname( "
"do.call( doTrace( dontCheck( double double( drop( droplevels( dump( duplicated( dyn.load( dyn.unload( dynGet( dynLibs( "
"eapply( eigen( emptyenv( enc2native( enc2utf8( encodeString( endsWith( enquote( "
"env.profile( environment environment( environmentIsLocked( environmentName( errorCondition( eval( eval.parent( evalq( "
"exists( exp( expand.grid( expm1( expression expression( extSoftVersion( externalptr "
"factor( factorial( fifo( file( file.access( file.append( file.choose( file.copy( file.create( file.exists( file.info( "
"file.link( file.mode( file.mtime( file.path( file.remove( file.rename( file.show( file.size( file.symlink( "
"find.package( findInterval( findRestart( floor( flush( "
"force( forceAndCall( formals( format( format.info( format.pval( format.zeros( formatC( formatDL( forwardsolve( "
"gamma( gc.time( gcinfo( gctorture( gctorture2( get( get0( getConnection( getDLLRegisteredRoutines( getHook( "
"getLoadedDLLs( getNativeSymbolInfo( getOption( getRversion( getSrcLines( getTaskCallbackNames( geterrmessage( "
"gettext( gettextf( getwd( globalCallingHandlers( globalenv( gregexpr( grep( grepRaw( grepl( grouping( gsub( "
"gzcon( gzfile( "
"handleSimpleError( "
"iconv( iconvlist( icuGetCollate( icuSetCollate( identical( identity( ifelse( infoRDS( inherits( "
"intToBits( intToUtf8( integer integer( interaction( interactive( intersect( "
"inverse.rle( invisible( invokeRestart( invokeRestartInteractively( is.R( is.array( is.atomic( "
"is.call( is.character( is.complex( is.data.frame( is.double( is.element( is.environment( is.expression( "
"is.factor( is.finite( is.function( is.infinite( is.integer( is.language( is.list( is.loaded( is.logical( is.matrix( "
"is.na( is.name( is.nan( is.null( is.numeric( is.object( is.ordered( is.pairlist( is.primitive( is.qr( "
"is.raw( is.recursive( is.symbol( is.table( is.unsorted( is.vector( isFALSE( isIncomplete( isNamespaceLoaded( isOpen( "
"isRestart( isS4( isSeekable( isSymmetric( isTRUE isTRUE( isatty( isdebugged( "
"jitter( julian( kappa( kappa_tri( kronecker( "
"l10n_info( labels( language lapply( lbeta( lchoose( length( lengths( letters levels( lfactorial( lgamma( "
"libPaths( libcurlVersion( library( library.dynam( library.dynam.unload( licence( license( "
"list list( list.dirs( list.files( list2DF( list2env( load( loadNamespace( loadedNamespaces( "
"local( lockBinding( lockEnvironment( log( log10( log1p( log2( logb( logical logical( lower.tri( "
"make.names( make.unique( makeActiveBinding( makeMessage( mapply( margin.table( marginSums( "
"mat.or.vec( match( match.arg( match.call( match.fun( matrix( max( max.col( "
"mean( mem.maxNSize( mem.maxVSize( memCompress( memDecompress( memory.profile( merge( message( mget( min( missing( "
"mode( month.abb month.name months( mostattributes( "
"names( nargs( nchar( ncol( new.env( ngettext( nlevels( noquote( norm( normalizePath( nrow( "
"nullfile( numeric( numeric_version( nzchar( "
"objects( oldClass( on.exit( onAttach( onDetach( onLoad( onUnload( open( options( order( ordered( outer( "
"packBits( packageEvent( packageNotFoundError( packageStartupMessage( package_version( packages( pairlist pairlist( "
"parent.env( parent.frame( parse( paste( paste0( path.expand( path.package( pcre_config( pipe( plot( "
"pmatch( pmax( pmax.int( pmin( pmin.int( polyroot( pos.to.env( "
"pretty( prettyNum( print( prmatrix( proc.time( prod( promise prop.table( proportions( provideDimnames( psigamma( "
"pushBack( pushBackLength( "
"qr.Q( qr.R( qr.X( qr.coef( qr.fitted( qr.qty( qr.qy( qr.resid( qr.solve( quarters( quit( quote( "
"range( rank( rapply( raw raw( rawConnection( rawConnectionValue( rawShift( rawToBits( rawToChar( rbind( rcond( "
"read.dcf( readBin( readChar( readLines( readRDS( readRenviron( readline( reg.finalizer( regexec( regexpr( regmatches( "
"remove( removeTaskCallback( rep( rep.int( rep_len( replace( replicate( require( requireNamespace( "
"restartDescription( restartFormals( retracemem( returnValue( rev( rle( "
"round( row( row.names( rowMeans( rowNamesDF( rowSums( rownames( rowsum( "
"sQuote( sample( sample.int( sapply( save( save.image( saveRDS( scale( scan( search( searchpaths( seek( "
"seq( seq.int( seq_along( seq_len( sequence( serialize( serverSocket( "
"set.seed( setHook( setSessionTimeLimit( setTimeLimit( setdiff( setequal( setwd( "
"shQuote( shell( shell.exec( showConnections( sign( signalCondition( signalSimpleWarning( signif( "
"simpleCondition( simpleError( simpleMessage( simpleWarning( simplify2array( sin( single( sink( sink.number( sinpi( "
"slice.index( socketAccept( socketConnection( socketSelect( socketTimeout( solve( sort( sort.int( sort.list( source( "
"special split( sprintf( sqrt( srcfile( srcfilealias( srcfilecopy( srcref( "
"standardGeneric( standard_regexps( startsWith( stderr( stdin( stdout( stop( stopifnot( storage.mode( "
"str2expression( str2lang( strrep( strsplit( strtoi( strtrim( structure( strwrap( "
"sub( subset( substitute( substr( substring( sum( summary( "
"suppressMessages( suppressPackageStartupMessages( suppressWarnings( suspendInterrupts( svd( sweep( symbol "
"sys.call( sys.calls( sys.frame( sys.frames( sys.function( sys.nframe( sys.on.exit( sys.parent( sys.parents( "
"sys.source( sys.status( system( system.file( system.time( system2( "
"table( tabulate( tan( tanpi( tapply( taskCallbackManager( tcrossprod( "
"tempdir( tempfile( textConnection( textConnectionValue( toString( tolower( topenv( toupper( "
"trace( traceback( tracemem( tracingState( transform( trigamma( trimws( trunc( truncate( "
"try( tryCatch( tryInvokeRestart( tryResumeInterrupt( typeof( "
"unclass( undebug( union( unique( unlink( unlist( unloadNamespace( unlockBinding( unname( unserialize( unsplit( "
"untrace( untracemem( unz( upper.tri( url( utf8ToInt( "
"validEnc( validUTF8( vapply( vector( version "
"warning( warningCondition( weakref weekdays( which( "
"with( withAutoprint( withCallingHandlers( withRestarts( withVisible( within( "
"write( write.dcf( writeBin( writeChar( writeLines( "
"xor( xtfrm( xzfile( zapsmall( "

, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_R[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_R_KEYWORD, NP2StyleX_Keyword, L"bold; fore:#FF8000" },
	{ SCE_R_DIRECTIVE, NP2StyleX_Directive, L"fore:#FF8000" },
	{ SCE_R_FUNCTION, NP2StyleX_Function, L"fore:#A46000" },
	{ SCE_R_COMMENT, NP2StyleX_Comment, L"fore:#608060" },
	{ MULTI_STYLE(SCE_R_STRING, SCE_R_STRING2, 0, 0), NP2StyleX_String, L"fore:#008000" },
	{ SCE_R_ESCAPECHAR, NP2StyleX_EscapeSequence, L"fore:#0080C0" },
	{ SCE_R_BACKTICKS, NP2StyleX_Backticks, L"fore:#7C5AF3" },
	{ SCE_R_NUMBER, NP2StyleX_Number, L"fore:#FF0000" },
	{ MULTI_STYLE(SCE_R_OPERATOR, SCE_R_INFIX, 0, 0), NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexR = {
	SCLEX_R, NP2LEX_R,
	EDITLEXER_HOLE(L"R Code", Styles_R),
	L"r; rsource",
	&Keywords_R,
	Styles_R
};
