#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_Typst = {{
//++Autogenerated -- start of section automatically generated
"and as auto break context continue else false for if import in include let none not or return set show true while "

, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_Typst[] = {
	EDITSTYLE_DEFAULT,
	{ SCE_TYPST_HEADER1, NP2StyleX_Header1, L"bold; fore:#0080FF" },
	{ SCE_TYPST_HEADER2, NP2StyleX_Header2, L"bold; fore:#0066CC" },
	{ SCE_TYPST_HEADER3, NP2StyleX_Header3, L"bold; fore:#0080C0" },
	{ SCE_TYPST_HEADER4, NP2StyleX_Header4, L"bold; fore:#007F7F" },
	{ SCE_TYPST_HEADER5, NP2StyleX_Header5, L"bold; fore:#408080" },
	{ SCE_TYPST_HEADER6, NP2StyleX_Header6, L"bold; fore:#408040" },
	{ SCE_TYPST_KEYWORD, NP2StyleX_Keyword, L"bold; fore:#FF8000" },
	{ SCE_TYPST_FUNCTION, NP2StyleX_Function, L"fore:#A46000" },
	{ MULTI_STYLE(SCE_TYPST_COMMENT_LINE, SCE_TYPST_COMMENT_BLOCK, 0, 0), NP2StyleX_Comment, L"fore:#608060" },
	{ SCE_TYPST_STRING, NP2StyleX_String, L"fore:#008000" },
	{ SCE_TYPST_MATH_DELIMITER, NP2StyleX_Math, L"fore:#008000" },
	{ SCE_TYPST_MATH_SYMBOL, NP2StyleX_Symbol, L"fore:#7C5AF3" },
	{ MULTI_STYLE(SCE_TYPST_OLIST_ITEM, SCE_TYPST_OLIST_NUM, 0, 0), NP2StyleX_OrderedList, L"bold; fore:#0080FF" },
	{ SCE_TYPST_ULIST_ITEM, NP2StyleX_UnorderedList, L"bold; fore:#0080FF" },
	{ SCE_TYPST_DEFINITION_LIST, NP2StyleX_DefinitionList, L"bold; fore:#0080FF" },
	{ SCE_TYPST_EM, NP2StyleX_Emphasis, L"italic" },
	{ SCE_TYPST_STRONG, NP2StyleX_Strong, L"bold" },
	{ SCE_TYPST_CODE_SPAN, NP2StyleX_InlineCode, L"back:#C5C5C5" },
	{ SCE_TYPST_CODE_BLOCK, NP2StyleX_CodeBlock, L"back:#C5C5C5; eolfilled" },
	{ SCE_TYPST_ESCAPECHAR, NP2StyleX_EscapeSequence, L"fore:#0080C0" },
	{ SCE_TYPST_HARD_LINE_BREAK, NP2StyleX_HardLineBreak, L"fore:#C80000; back:#8080FF" },
	{ SCE_TYPST_PROPERTY, NP2StyleX_Property, L"fore:#648000" },
	{ SCE_TYPST_REFERENCE, NP2StyleX_Variable, L"fore:#9E4D2A" },
	{ SCE_TYPST_LABEL, NP2StyleX_Label, L"fore:#3A6EA5" },
	{ MULTI_STYLE(SCE_TYPST_NUMBER, SCE_TYPST_NUMBER_MATH, 0, 0), NP2StyleX_Number, L"fore:#3A6EA5" },
	{ SCE_TYPST_OPERATOR, NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexTypst = {
	SCLEX_TYPST, NP2LEX_TYPST,
//Settings++Autogenerated -- start of section automatically generated
		LexerAttr_EscapePunctuation,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0) | (1 << 1) | (1 << 2), // header1, header2, header3
		0,
		'\\', SCE_TYPST_ESCAPECHAR, 0,
		0,
		0, SCE_TYPST_OPERATOR,
		SCE_TYPST_OPERATOR, 0
		, KeywordAttr32(0, KeywordAttr_PreSorted) // keywords
		, SCE_TYPST_COMMENT_BLOCK,
		SCE_TYPST_STRING, SCE_TYPST_ESCAPECHAR,
//Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"Typst File", Styles_Typst),
	L"typ",
	&Keywords_Typst,
	Styles_Typst
};
