#include "EditLexer.h"
#include "EditStyleX.h"

static KEYWORDLIST Keywords_VBS = {{
//++Autogenerated -- start of section automatically generated
"Alias And As Attribute Begin Boolean ByRef Byte ByVal Call Case Char Class Compare Const Continue Currency "
"Decimal Declare Default Dim Do Double "
"Each Else ElseIf Empty End EndIf Enum Eqv Erase Error Event Execute ExecuteGlobal Exit Explicit "
"False For Friend Function Get Global GoSub GoTo If Imp Implements In Integer Is "
"Let Lib Like Load Long LongLong LongPtr Loop LSet Me Mod Module New Next Not Nothing Null Object On Option Optional Or "
"ParamArray Preserve Private Property Public RaiseEvent Randomize ReDim Rem Resume Return RSet "
"Select Set Shared Single Static Step Stop String Sub Then To True Type TypeOf Unload Until Variant "
"Wend While With WithEvents Xor "

, // 1 type keyword
nullptr

, // 2 VBA keyword
nullptr

, // 3 preprocessor
nullptr

, // 4 attribute
nullptr

, // 5 class
"ActiveXObject Debug Dictionary Err FileSystemObject RegExp WScript "

, // 6 interface
nullptr

, // 7 enumeration
nullptr

, // 8 constant
"vbAbort vbAbortRetryIgnore vbApplicationModal vbArray vbBinaryCompare vbBlack vbBlue vbBoolean vbByte "
"vbCancel vbCr vbCritical vbCrLf vbCurrency vbCyan "
"vbDataObject vbDate vbDecimal vbDefaultButton1 vbDefaultButton2 vbDefaultButton3 vbDefaultButton4 vbDouble "
"vbEmpty vbError vbExclamation vbFalse vbFirstFourDays vbFirstFullWeek vbFirstJan1 vbFormFeed vbFriday "
"vbGeneralDate vbGreen vbIgnore vbInformation vbInteger vbLf vbLong vbLongDate vbLongTime vbMagenta vbMonday "
"vbNewLine vbNo vbNull vbNullChar vbNullString vbObject vbObjectError vbOK vbOKCancel vbOKOnly vbQuestion "
"vbRed vbRetry vbRetryCancel vbSaturday vbShortDate vbShortTime vbSingle vbString vbSunday vbSystemModal "
"vbTab vbTextCompare vbThursday vbTrue vbTuesday vbUseDefault vbUseSystemDayOfWeek vbVariant vbVerticalTab "
"vbWednesday vbWhite vbYellow vbYes vbYesNo vbYesNoCancel "

, // 9 basic function
"Abs( Array( Asc( Atn( CBool( CByte( CCur( CDate( CDbl( Chr( CInt( CLng( Cos( CreateObject( CSng( CStr( "
"Date DateAdd( DateDiff( DatePart( DateSerial( DateValue( Day( Escape( Eval( Exp( "
"Filter( Fix( FormatCurrency( FormatDateTime( FormatNumber( FormatPercent( GetLocale( GetObject( GetRef( Hex( Hour( "
"InputBox( InStr( InStrRev( Int( IsArray( IsDate( IsEmpty( IsNull( IsNumeric( IsObject( Join( "
"LBound( LCase( Left( Len( LoadPicture( Log( LTrim( Mid( Minute( Month( MonthName( MsgBox( Now Oct( "
"Replace( RGB( Right( Rnd Round( RTrim( "
"ScriptEngine ScriptEngineBuildVersion ScriptEngineMajorVersion ScriptEngineMinorVersion Second( SetLocale( Sgn( Sin( "
"Space( Split( Sqr( StrComp( String( StrReverse( "
"Tan( Time Timer TimeSerial( TimeValue( Trim( TypeName( UBound( UCase( Unescape( VarType( Weekday( WeekdayName( Year( "

, // 10 misc
"Add( AtEndOfLine AtEndOfStream BuildPath( "
"Clear( Close( Column CompareMode CopyFile( CopyFolder( Count CreateFolder( CreateTextFile( "
"DeleteFile( DeleteFolder( Description DriveExists( Drives Execute( Exists( FileExists( FirstIndex FolderExists( "
"GetAbsolutePathName( GetBaseName( GetDrive( GetDriveName( GetExtensionName( "
"GetFile( GetFileName( GetFileVersion( GetFolder( GetParentFolderName( GetSpecialFolder( GetStandardStream( GetTempName( "
"HelpContext HelpFile IgnoreCase Item( Items( Key( Keys( Length Line MoveFile( MoveFolder( Number "
"OpenAsTextStream( OpenTextFile( Pattern Raise( Read( ReadAll( ReadLine( Remove( RemoveAll( Skip( SkipLine( Source Test( "
"Value Write( WriteBlankLines( WriteLine( "

, nullptr, nullptr, nullptr, nullptr, nullptr
//--Autogenerated -- end of section automatically generated
}};

static EDITSTYLE Styles_VBS[] = {
	EDITSTYLE_DEFAULT,
	{ MULTI_STYLE(SCE_VB_KEYWORD, SCE_VB_KEYWORD2, SCE_VB_KEYWORD3, 0), NP2StyleX_Keyword, L"fore:#0000FF" },
	{ SCE_VB_CLASS, NP2StyleX_Class, L"bold; fore:#007F7F" },
	{ SCE_VB_BASIC_FUNCTION, NP2StyleX_BasicFunction, L"fore:#0080C0" },
	{ SCE_VB_FUNCTION_DEFINITION, NP2StyleX_FunctionDefinition, L"bold; fore:#A46000" },
	{ SCE_VB_CONSTANT, NP2StyleX_Constant, L"fore:#B000B0" },
	{ SCE_VB_COMMENTLINE, NP2StyleX_Comment, L"fore:#608060" },
	{ SCE_VB_STRING, NP2StyleX_String, L"fore:#008000" },
	{ SCE_VB_DATE, NP2StyleX_DateTime, L"fore:#008080" },
	{ SCE_VB_LABEL, NP2StyleX_Label, L"back:#FFC040" },
	{ SCE_VB_NUMBER, NP2StyleX_Number, L"fore:#FF0000" },
	{ MULTI_STYLE(SCE_VB_OPERATOR, SCE_VB_OPERATOR2, SCE_VB_LINE_CONTINUATION, 0), NP2StyleX_Operator, L"fore:#B000B0" },
};

EDITLEXER lexVBScript = {
	SCLEX_VISUALBASIC, NP2LEX_VBSCRIPT,
//Settings++Autogenerated -- start of section automatically generated
		LexerAttr_NoBlockComment,
		TAB_WIDTH_4, INDENT_WIDTH_4,
		(1 << 0), // function
		SCE_VB_FUNCTION_DEFINITION,
		'\0', SCE_VB_ESCAPECHAR, SCE_VB_FORMAT_SPECIFIER,
		0,
		0, SCE_VB_COMMENTLINE,
		SCE_VB_OPERATOR, SCE_VB_OPERATOR2
		, KeywordAttr32(0, KeywordAttr_MakeLower | KeywordAttr_PreSorted) // keywords
		| KeywordAttr32(1, KeywordAttr_MakeLower) // type keyword
		| KeywordAttr32(2, KeywordAttr_MakeLower) // VBA keyword
		| KeywordAttr32(3, KeywordAttr_MakeLower | KeywordAttr_NoAutoComp) // preprocessor
		| KeywordAttr32(4, KeywordAttr_MakeLower) // attribute
		| KeywordAttr32(5, KeywordAttr_MakeLower | KeywordAttr_PreSorted) // class
		| KeywordAttr32(6, KeywordAttr_MakeLower) // interface
		| KeywordAttr64(7, KeywordAttr_MakeLower) // enumeration
		| KeywordAttr64(8, KeywordAttr_MakeLower | KeywordAttr_PreSorted) // constant
		| KeywordAttr64(9, KeywordAttr_MakeLower | KeywordAttr_PreSorted) // basic function
		| KeywordAttr64(10, KeywordAttr_NoLexer) // misc
		, SCE_VB_COMMENTLINE,
		SCE_VB_STRING, SCE_VB_PLACEHOLDER,
//Settings--Autogenerated -- end of section automatically generated
	EDITLEXER_HOLE(L"VBScript", Styles_VBS),
	L"vbs; dsm",
	&Keywords_VBS,
	Styles_VBS
};
